afterInstall: yarn get-esm-packages -p yarnv2+ -r --file esm-packages.json --quiet

compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

plugins:
  - checksum: 0a2a35fbed2f33f0df1ceb1db51bf72554201f994eaecb86cbc62a295c3d05f7cc44fa8be8e64fc5e1c0bee4f529a17a0cc429ea9e3486ad467443291d5a8e3b
    path: .yarn/plugins/@yarnpkg/plugin-after-install.cjs
    spec: "https://raw.githubusercontent.com/mhassan1/yarn-plugin-after-install/refs/tags/v0.6.0/bundles/%40yarnpkg/plugin-after-install.js"
  - checksum: dd1402820c9f1be4f23995511109ef5110d44502498f59e7f637d6771bce032aafffba0042842f4c9cd3ea5fc4faa0cafdad023cfbd554aa2f1f4bb00711b3fb
    path: .yarn/plugins/correct-yarn-formatting.cjs
    spec: "https://raw.githubusercontent.com/HanseltimeIndustries/correct-yarn-formatting/v1.0.1/lib/index.js"
