site_name: '@hanseltime/pkgtest'
theme:
  name: material
  features:
    - content.code.copy
    - content.code.select
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
