site_name: '@hanseltime/pkgtest'
repo_url: https://github.com/HanseltimeIndustries/pkgtest
theme:
  name: material
  features:
    - content.code.copy
    - content.code.select
    - toc.follow
    - navigation.top
    - navigation.tabs
    - navigation.tracking
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
extra:
  version:
    provider: mike