name: Release
run-name: ${{ github.ref_name }} Release

on:
  push:
    branches: 
      - main
      - alpha

jobs:
  call-test-workflow:
    uses: ./.github/workflows/test-flow.yaml
    with:
      from: ${{ github.workflow }}
  release:
    runs-on: ubuntu-latest
    needs: call-test-workflow

    steps:
      # Use our auto-commit permissioned app for our git actions
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.AUTO_COMMIT_APP_ID }}
          private-key: ${{ secrets.AUTO_COMMIT_APP_PKEY }}
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: Enable yarn Berry
        run: corepack enable
      - name: Install
        run: |
          yarn install --immutable
          # Hack - the yarn team refuses to not take over formatting the package.json
          git checkout package.json
      - name: Build
        run: yarn build
      - name: Publish documentation
        run: |
          pip install -r docs/requirements.txt
          git config user.name docs-bot
          git config user.email docs-bot@hanseltime.com
          ./bin/publish-docs.sh 0.1.0-test
      # - name: Release
      #   run: yarn release
      #   env:
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      #     GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
